---
- name: NFS Server Configuration
  hosts: salem
  vars:
    name_pkg: nfs-utils
    name_service: nfs-server 
  tasks:
    - name: Install software in 136.33
      yum:
        name:
          - "{{name_pkg}}"
        state: latest
    - name: Start the Service
      service: 
        name:
          - "{{name_service}}"
        state: started 
    - name: Enable the NFS-SERVER service
      service:
        name:
          - "{{name_service}}"
        enabled: yes
    - name: Create share
      file:
        path: /developer
        state: directory
    - name: To add Content in Exports
      lineinfile:
        path: /etc/exports
        line: "/developer 192.168.136.34(ro)"
    - name: Exports to OS
      shell: | 
         exportfs –r
    - name: To allow NFS in Firewall
      firewalld:
        service: nfs
        state: enabled
        immediate: yes
        permanent: yes
...
